---

- name: create normal users
  mongodb_user:
    database: "{{ item.database }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    replica_set: "{{ mongodb_conf_replSet }}"
    login_host: 127.0.0.1
    login_user: "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
  with_items:
    - "{{ mongodb_users }}"
  when: mongodb_users is defined and ansible_local.mongodb.mongodb.mongodb_login_port is undefined
  run_once: true

- name: create normal users port=yes
  mongodb_user:
    database: "{{ item.database }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    replica_set: "{{ mongodb_conf_replSet }}"
    login_host: 127.0.0.1
    login_port: "{{ ansible_local.mongodb.mongodb.mongodb_login_port }}"
    login_user: "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
  with_items:
    - "{{ mongodb_users }}"
  when: mongodb_users is defined and ansible_local.mongodb.mongodb.mongodb_login_port is defined
  run_once: true
