---

- include_vars: "{{ansible_distribution}}.yml"

- name: Add yum repository
  template: src=mongodb.RedHat.repo.j2 dest=/etc/yum.repos.d/mongodb.repo owner=root group=root mode=0644
  when: '"mongodb-org" in mongodb_package'

- name: Install MongoDB package
  yum: pkg={{mongodb_package}} state=present

- name: Install additional packages
  yum: pkg={{item}}
  with_items: mongodb_additional_packages
  when: mongodb_additional_packages is defined

- name: Remove default init script
  file: path=/etc/init.d/mongod state=absent
  when: mongodb_daemon_name != "mongod"

- name: Create customized init script
  template: src=mongodb.redhat.init dest=/etc/init.d/{{ mongodb_daemon_name }}
